name: Actions

on: [push]

permissions:
  contents: write

jobs:
  lint:
    name: lint
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install
      
      - name: Run eslint
        run: yarn lint

      - name: Run prettier
        run: yarn check-format

  build:
    name: build
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    container:
      image: node:20.15.1

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build
        id: build
        run: yarn build

  build-and-deploy:
    name: build and deploy
    if: github.ref == 'refs/heads/main'
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: yarn install
      - run: yarn build
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.